apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: das-operator
    app.kubernetes.io/instance: servicemonitor
    app.kubernetes.io/managed-by: das-operator
    app.kubernetes.io/name: das-operator-servicemonitor
    app.kubernetes.io/part-of: das-operator
  name: das-operator-servicemonitor
  namespace: das-operator
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - das-operator
  selector:
    matchLabels:
      app.kubernetes.io/name: das-operator-metrics