apiVersion: v1
kind: Pod
metadata:
  name: cuda-vectoradd-1
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-vectoradd-1
    image: "quay.io/tardieu/vectoradd:0.1.0"
    resources:
      limits:
        nvidia.com/mig-1g.5gb: 1
    command:
      - sh
      - -c
      -  "nvidia-smi -L; ./vectorAdd && sleep inf"
      # requests:
      #   cpu: 1000m
      #   memory: 512Mi
